default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  <<: *default
  database: culinary_suite_development
  username: Fabricio
  password: F@bricio20
  host: localhost

test:
  <<: *default
  database: culinary_suite_test
  username: Fabricio
  password: F@bricio20
  host: localhost
#
production:
  primary: &primary_production
    <<: *default
    database: culinary_suite_production
    username: culinary_suite
    password: <%= ENV["CULINARY_SUITE_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: culinary_suite_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: culinary_suite_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: culinary_suite_production_cable
    migrations_paths: db/cable_migrate
